"$schema" = 'https://starship.rs/config-schema.json'
starship_precmd_user_func=""
add_newline = true
command_timeout = 5000
scan_timeout = 5000
palette = 'foo'
format = """
[â•­â”€â”¤](bold lav)\ 
$username$hostname $directory\ 
$git_branch$git_status$git_state$git_metrics
[â•°â”€â”€â•¼](bold lav)$jobs$character
"""
right_format = """
$aws$c$cmake$docker_context$golang$kubernetes$lua$nix_shell$nodejs$ruby$rust$zig\
$package$cmd_duration$memory_usage$time
"""
continuation_prompt = "[â–¶â–¶](bold lav)"

[sudo]
format = '[ã€š[as $symbol]ã€›](lav)'

[character]
#"format = "[  âœ](green) "
success_symbol = "[ I  âœ](bold green) "
error_symbol = "[ I  âœ–](bold red) "
vimcmd_symbol = "[ N  < ](bold yellow)"
vimcmd_replace_one_symbol = "[ R  < ](bold purple)"
vimcmd_replace_symbol = "[ R  < ](bold purple)"
vimcmd_visual_symbol = "[ V  < ](bold blue)"

[username]
format = '[ î° ]($style) '
show_always = true

[directory]
truncation_length=3
truncate_to_repo=true
home_symbol = '~'
fish_style_pwd_dir_length=3
truncation_symbol = ''
[directory.substitutions]
'~/projects/' = 'www/'
'~/.dotfiles/' = '.d/'
'~/.config/' = '.c/'

[package]
disabled = false
format = '[<](lav)[$symbol$version]($style)[>](lav)'

[cmd_duration]
format = ' [took $duration]($style)'

[jobs]
symbol = "âœ¦"
symbol_threshold = 1
number_threshold = 2

[time]
format = '[ã€š](lav)[$time]($style)[ã€›](lav)'

[hostname]
format='@ [$ssh_symbol$hostname]($style)'

## Git
[git_branch]
format = '[git:](lav)[$branch $symbol]($style)'
# format = '[Â·](bold lav)[git:](lav)[$branch $symbol]($style)'

[git_status]
format = '[\(](lav)[$all_status$ahead_behind]($style)[\)](lav)'
ignore_submodules = true

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

## Colors
[palettes.foo]
lav = '#8A83B8'

## Languages
[aws]
format = '[ã€š [$symbol($profile)(\($region\))( ($duration)]($style)ã€›](lav)'

[c]
format = '[ã€š [$symbol($version(-$name))]($style) ã€›](lav)'

[cmake]
format = '[ã€š [$symbol($version)]($style) ã€›](lav)'

[docker_context]
format = '[ã€š [$symbol$context]($style) ã€›](lav)'

[golang]
format = '[ã€š [$symbol($version)]($style) ã€›](lav)'

# [java]
# format = '[ã€š [$symbol($version)]($style) ã€›](lav)'

[kubernetes]
format = '[ã€š [$symbol$context( \($namespace\))]($style) ã€›](lav)'

[lua]
format = '[ã€š [ï†† ($version)](bold blue) ã€›](lav)'

[nix_shell]
format = '[ã€š [$symbol$state( \($name\))]($style) ã€›](lav)'

[nodejs]
format = '[ã€š [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) ã€›](lav)'

[ruby]
format = '[ã€š [$symbol($version)]($style) ã€›](lav)'

[rust]
format = '[ã€š](lav) [$symbol($version)]($style) [ã€›](lav)'

[zig]
format = '[ã€š [$symbol($version)]($style) ã€›](lav)'
