add_newline = true
command_timeout = 1000
format = """$character"""
right_format = """$all"""
continuation_prompt = "â–¶â–¶"

[aws]
format = ' îªµ[$symbol($profile)(\($region\))( îªµ$durationîª¶)]($style)îª¶'

[bun]
format = ' îªµ[$symbol($version)]($style)îª¶'

[c]
format = ' îªµ[$symbol($version(-$name))]($style)îª¶'

[character]
#"format = "[  âœ](green) "
success_symbol = "[ I  âœ](bold green) "
error_symbol = "[ I  âœ–](bold red) "
vimcmd_symbol = "[ N  â® ](bold yellow)"
vimcmd_replace_one_symbol = "[ R  â® ](bold purple)"
vimcmd_replace_symbol = "[ R  â® ](bold purple)"
vimcmd_visual_symbol = "[ V  â® ](bold blue)"

[cmake]
format = ' îªµ[$symbol($version)]($style)îª¶'

[cmd_duration]
format = ' îªµ[took $duration]($style)îª¶'

[cobol]
format = ' îªµ[$symbol($version)]($style)îª¶'

[conda]
format = ' îªµ[$symbol$environment]($style)îª¶'

[crystal]
format = ' îªµ[$symbol($version)]($style)îª¶'

[daml]
format = ' îªµ[$symbol($version)]($style)îª¶'

[dart]
format = ' îªµ[ğŸ¯($version) ]($style)îª¶'

[deno]
format = ' îªµ[$symbol($version)]($style)îª¶'

[docker_context]
format = ' îªµ[$symbol$context]($style)îª¶'

[dotnet]
format = ' îªµ[$symbol($version)(ğŸ¯ $tfm)]($style)îª¶'

[elixir]
format = ' îªµ[$symbol($version \(OTP $otp_version\))]($style)îª¶'

[elm]
format = ' îªµ[$symbol($version)]($style)îª¶'

[erlang]
format = ' îªµ[$symbol($version)]($style)îª¶'

[gcloud]
format = ' îªµ[$symbol$account(@$domain)(\($region\))]($style)îª¶'

[git_branch]
format = '[$symbol$branch]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style))'
ignore_submodules = true

[golang]
format = ' îªµ[$symbol($version)]($style)îª¶'

[haskell]
format = ' îªµ[$symbol($version)]($style)îª¶'

[helm]
format = ' îªµ[$symbol($version)]($style)îª¶'

[hg_branch]
format = ' îªµ[$symbol$branch]($style)îª¶'

[java]
format = ' îªµ[$symbol($version)]($style)îª¶'

[jobs]
symbol = "âœ¦"
symbol_threshold = 1
number_threshold = 2

[julia]
format = ' îªµ[$symbol($version)]($style)îª¶'

[kotlin]
format = ' îªµ[$symbol($version)]($style)îª¶'

[kubernetes]
format = ' îªµ[$symbol$context( \($namespace\))]($style)îª¶'

[lua]
format = ' îªµ[ï†† ($version)](bold blue)îª¶'

[memory_usage]
format = ' îªµ$symbol[$ram( | $swap)]($style)îª¶'

[nim]
format = ' îªµ[$symbol($version)]($style)îª¶'

[nix_shell]
format = ' îªµ[$symbol$state( \($name\))]($style)îª¶'

[nodejs]
format = ' îªµ[$symbol($version)]($style)îª¶'

[ocaml]
format = ' îªµ[$symbol($version)(\($switch_indicator$switch_name\))]($style)îª¶'

[openstack]
format = ' îªµ[$symbol$cloud(\($project\))]($style)îª¶'

[package]
disabled = true
format = ' îªµ[$symbol$version]($style)îª¶'

[perl]
format = ' îªµ[$symbol($version)]($style)îª¶'

[php]
format = ' îªµ[$symbol($version)]($style)îª¶'

[pulumi]
format = ' îªµ[$symbol$stack]($style)îª¶'

[purescript]
format = ' îªµ[$symbol($version)]($style)îª¶'

[python]
format = ' îªµ[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)îª¶'

[raku]
format = ' îªµ[$symbol($version-$vm_version)]($style)îª¶'

[red]
format = ' îªµ[$symbol($version)]($style)îª¶'

[ruby]
format = ' îªµ[$symbol($version)]($style)îª¶'

[rust]
format = ' îªµ[$symbol($version)]($style)îª¶'

[scala]
format = ' îªµ[$symbol($version)]($style)îª¶'

[spack]
format = ' îªµ[$symbol$environment]($style)îª¶'

[sudo]
format = ' îªµ[as $symbol]îª¶'

[swift]
format = ' îªµ[$symbol($version)]($style)îª¶'

[terraform]
format = ' îªµ[$symbol$workspace]($style)îª¶'

[time]
format = ' îªµ[$time]($style)îª¶'

[username]
format = '[ î° ]($style) '
show_always = true

[vagrant]
format = ' îªµ[$symbol($version)]($style)îª¶'

[vlang]
format = ' îªµ[$symbol($version)]($style)îª¶'

[zig]
format = ' îªµ[$symbol($version)]($style)îª¶'
